### ISSUE TITLE
Can you use this project with DNX Core?

### ISSUE THREAD

**Issue by akashamar** [louislewis2/Aurelia-Demo#3]
Hi @louislewis2,

I tried adding dnxcore50 to project.json but compilation failed.
Is there a way to use this project with asp.net 5 core?

Regards.

**Comment by louislewis2** [comment]
I am taking a look now, I removed it previously because the previous version of IdentityServer was not working with core, and I have not tried since I updated to their V2 release. I will let you know as soon as I am done checking things out.

**Comment by louislewis2** [comment]
Still the same issue as before. The released IdentityServer3 V2.0 library still does not seem ready to support core50.

**Comment by akashamar** [comment]
Windows server nano does not support dnx45...
Do you know if there is a beta version that supports dnxcore50?

**Comment by louislewis2** [comment]
I just got word moments ago that there is talk between Microsoft and Thinktecture regarding IdentityServer. If the deal is made, we would most likely see a build ready for core50 very soon.

**Comment by akashamar** [comment]
Ok thanks @louislewis2 

I found this question in the asp.net repo: https://github.com/aspnet/Security/issues/359
Do you think this code can be used with aurelia?

// don't use this code as-is in production scince ValidateSignature is false
app.Use(async (context, next) =>
{
    var authType = IdentityOptions.ApplicationCookieAuthenticationType;
    var authScheme = IdentityOptions.ApplicationCookieAuthenticationScheme;
    if (context.Request.Path.ToString().ToLower() == "/token")
    {
        // Generate Token
        if (!context.Request.HasFormContentType || !context.Request.Form.ContainsKey("username") || !context.Request.Form.ContainsKey("password"))
        {
            context.Response.StatusCode = (int)System.Net.HttpStatusCode.Unauthorized;
            return;
        }
        var userName = context.Request.Form["username"];
        var password = context.Request.Form["password"];
        var userManager = context.ApplicationServices.GetRequiredService<UserManager<ApplicationUser>>();
        var user = await userManager.Users.FirstAsync(u => u.UserName == userName);
        if (!await userManager.CheckPasswordAsync(user, password))
        {
            context.Response.StatusCode = (int)System.Net.HttpStatusCode.Unauthorized;
            return;
        }
        var roles = await userManager.GetRolesAsync(user);
        var claims = new List<Claim>(new Claim[] { new Claim(ClaimTypes.Name, user.UserName) });
        foreach (var r in roles) claims.Add(new Claim(ClaimTypes.Role, r));
        foreach (var c in user.Claims) claims.Add(new Claim(c.ClaimType, c.ClaimValue));
        var identity = new ClaimsIdentity(claims, authScheme);
        var handler = new JwtSecurityTokenHandler();
        var rsa = new RSACryptoServiceProvider(2048);
        var rsaParams = rsa.ExportParameters(true);
        var rsaKey = new RsaSecurityKey(rsaParams);
        var secToken = handler.CreateToken("myself", "myself", identity, DateTime.UtcNow, DateTime.UtcNow.AddDays(1),
            new SigningCredentials(rsaKey, JwtAlgorithms.RSA_SHA256, JwtAlgorithms.RSA_SHA256, "yourkeyid"));
        var token = handler.WriteToken(secToken);
        List<string> tokens = null;
        if (app.Properties.ContainsKey("tokens"))
            tokens = (List<string>)app.Properties["tokens"];
        else
        {
            tokens = new List<string>();
            app.Properties.Add("tokens", tokens);
        }
        tokens.Add(token);
        await context.Response.WriteAsync(string.Format("{{\"token_type\":\"{0}\",\"access_token\":\"{1}\"}}", "bearer", token));
        return;
    }
    else if (!context.User.Identities.Any(identity => identity.IsAuthenticated) &&
            context.Request.Path.StartsWithSegments(new PathString("/api")))
    {
        // Validate Token
        var token = context.Request.Headers["Authorization"];
        var tokens = app.Properties.ContainsKey("tokens") ? (List<string>)app.Properties["tokens"] : null;
        if (string.IsNullOrEmpty(token) || token.Substring(0, "bearer ".Length).ToLower() != "bearer " || tokens == null || tokens.Count == 0)
        {
            context.Response.StatusCode = (int)System.Net.HttpStatusCode.Unauthorized;
            return;
        }
        token = token.Substring("bearer ".Length);
        var handler = new JwtSecurityTokenHandler();
        var rsa = new RSACryptoServiceProvider(2048);
        var rsaParams = rsa.ExportParameters(true);
        var rsaKey = new RsaSecurityKey(rsaParams);
        var validationParameters = new TokenValidationParameters
        {
            ValidAudience = "myself",
            ValidIssuer = "myself",
            RequireExpirationTime = true,
            IssuerSigningKey = rsaKey,
            AuthenticationType = authType,
            RequireSignedTokens = true,
            ValidateAudience = true,
            ValidateIssuer = true,
            ValidateActor = false,
            ValidateIssuerSigningKey = true,
            ValidateSignature = false, // this feature should be fixed
            ValidateLifetime = true,
        };
        try
        {
            SecurityToken secToken;
            var principal = handler.ValidateToken(token, validationParameters, out secToken);
            principal.Identities.First().AddClaim(new Claim(ClaimTypes.AuthenticationMethod, authType));
            context.User = principal;
        }
        catch
        {
            tokens.Remove(token);
            context.Response.StatusCode = (int)System.Net.HttpStatusCode.Unauthorized;
            return;
        }
    }
    else if (context.Request.Path == "/signout")
    {
        // Remove Token
        var token = context.Request.Headers["Authorization"];
        var tokens = app.Properties.ContainsKey("tokens") ? (List<string>)app.Properties["tokens"] : null;
        if (string.IsNullOrEmpty(token) || token.Substring(0, "bearer ".Length).ToLower() != "bearer " || tokens == null || tokens.Count == 0)
            return;
        token = token.Substring("bearer ".Length);
        tokens.Remove(token);
        return;
    }
    await next();
});

@eqbalsajadi @leastprilege @pinpointtownes

**Comment by PinpointTownes** [comment]
@louislewis2 hey, it's definitely a small world. Glad to see you've progressed with your Aurelia sample :smile: 

@akashamar I'm not sure to understand how I could help you. It seems that @louislewis2 went with **IdSrv** so if you have a question about how to use it or about their plans for ASP.NET 5, it's probably better to ping **Dominick** or **Brock** on Gitter: https://gitter.im/IdentityServer/IdentityServer3.

Generally, the way an authorization/authentication server is implemented is not really relevant from the client application's perspective, as long as both sides use the same protocol (for instance, OAuth2 or OpenID Connect).

The snippet posted by @eqbalsajadi doesn't implement a standard/known protocol, so you'll probably have to update @louislewis2's sample to use the same protocol. Depending on whether this Aurelia demo implements the resource owner password credentials flow, it should be relatively easy. 

You could also take a look at `AspNet.Security.OpenIdConnect.Server`: unlike IdSrv, it's based on ASP.NET 5 and fully supports CoreCLR (aka `dnxcore50`). You can find more information on the topic you mentioned: https://github.com/aspnet/Security/issues/359#issuecomment-123214592 (an AngularJS sample is on the road).

**Comment by PinpointTownes** [comment]
After a brief look, it seems that this project implements the "resource owner password credentials grant type" (not correctly though, but that's another topic), so it shouldn't be hard to use @eqbalsajadi's approach: https://github.com/louislewis2/Aurelia-Demo/blob/authentication_features/src/AureliaDemo/dev/app/core/services/OpenIdService.ts#L45-L53

Good luck :no_good:

**Comment by louislewis2** [comment]
@akashamar @PinpointTownes 
The authentication feature of the project is still a work in progress, which is why it is still currently in
its own branch, and why it has not yet been merged back into master as yet. There is still a fair amount of work to do, before we can merge.

I will certainly take a look at the exact client implementation and find the best practices and implement any changes accordingly. I personally did not know that using resource owner or password credentials is not correct, I will certainly dig into this and fix where it is required. Thanks for highlighting this.

While on the subject of the client, I intend on implementing the security services against standards based endpoints, so in theory one should be able to swop out the server implementations for which ever a developer might want to use.

I went with IdentityServer3, simply because the bits where available without having to add custom nuget config files and risk potential viewers with having issues. I am also not suggesting that one identity provider is better than another, that is a argument I am not interested in, and would hope that developers can make that decision based on their own knowledge and research.

@leastprivilege Do you have any suggestions for our implementation of your server in this project?
Keeping in mind that it is still a work in progress :) This project is meant to serve as a community sample and having best practices implemented would make it that much better.

This project is destined to become a more full blown LOB application, we will be implementing the rest of the API soon enough to cover a order entry system. Authentication / Authorization was the first step towards that goal. And in that API, I would like to have both OpenId and OAuth2, simply because this is what people have asked for :)

**Comment by PinpointTownes** [comment]
> I will certainly take a look at the exact client implementation and find the best practices and implement any changes accordingly. I personally did not know that using resource owner or password credentials is not correct, I will certainly dig into this and fix where it is required. Thanks for highlighting this.

Using this OAuth2 grant type is not fundamentally wrong (though a large part of the community won't agree with me as it breaks the whole purpose of OAuth2: http://stackoverflow.com/a/31080006/542757 :smile:)

The problem with your sample is that you implemented "client authentication": https://github.com/louislewis2/Aurelia-Demo/blob/authentication_features/src/AureliaDemo/dev/app/core/services/OpenIdService.ts#L45-L47

JS apps are typically what the OAuth2 specs name "public clients" as they can't safely keep their credentials secret (you can easily use your browsers' tools to extract or intercept them): https://tools.ietf.org/html/rfc6749#section-2.1

Client authentication is not required with the resource owner password credentials grant type with public clients so you should simply remove it: https://tools.ietf.org/html/rfc6749#section-4.3.2

> And in that API, I would like to have both OpenId and OAuth2, simply because this is what people have asked for :)

FYI: the resource owner password credentials grant type is a pure OAuth2 thing. Though inheriting from OAuth2, OpenID Connect doesn't mention this grant type in its specs (since the writers' intention was clearly to avoid it).
